### ISSUE TITLE
Question about dataset directory

### ISSUE THREAD

**Issue by jjoon0928** [Noahsark/DADA#1]
Hello. When I am in the training phase, cars196 and sop dataset.

I tried to make a hierarchy of them:
```
dataset/
|---cars196
|      ㄴ---images
|                  ㄴ--- 000001.jpg
|                  ㄴ--- 000002.jpg
|                  ㄴ--- ...
|---online_products 
|      ㄴ---images
|                  ㄴ--- bicycle_final
|                               ㄴ 111085122871_0.JPG
|                  ㄴ--- cabinet_final
|                  ㄴ--- ...
|      ㄴ---Info_Files

```

However, cars196 show NotADirectoryError: [Errno 20] Not a directory: '~/dataset/cars196/images/000001.jpg'
and sop shows FileNotFoundError: [Errno 2] No such file or directory: '~/dataset/online_products/images/cabinet_final/331185934232_10.JPG' even though I added this image again.

And is there any code for visualizing features through t-SNE such as Figure 5 in your paper?

**Comment by Noahsark** [comment]
@jjoon0928  Hi, Thanks for being interested in our work. Have you solved this? May I ask what the whole error message was?

**Comment by jjoon0928** [comment]
> @jjoon0928 Hi, Thanks for being interested in our work. Have you solved this? May I ask what the whole error message was?

@Noahsark Hello, there are errors what I have seen.
**Cars196 dataset**
```
(venv) (base) ~@ubuntu:/~/DADA$ python main.py --source_path ../dataset --save_path train_savepoint --save_name test_cars --config configs/cars.yaml
Traceback (most recent call last):
  File "~/DADA/main.py", line 82, in <module>
    datasets = dataset_library.select(opt.dataset, opt, opt.source_path)
  File "~/DADA/datasets/__init__.py", line 10, in select
    return cars196.give_dataloaders(opt, data_path)
  File "~/DADA/datasets/cars196.py", line 31, in give_dataloaders
    image_list = {
  File "~/DADA/datasets/cars196.py", line 34, in <dictcomp>
    for x in os.listdir(image_sourcepath + '/' + key)
NotADirectoryError: [Errno 20] Not a directory: '../dataset/cars196/images/000001.jpg'
```

**SOP**
in the case SOP, the training is working in 0 epoch, but errors have occurred in testing metric phase.
```
Computing Testing Metrics...
[Compute Test]: 13.65% [46/337, 00:10/01:05]
Traceback (most recent call last):
  File "~/DADA/main.py", line 408, in <module>
    eval.evaluate(opt.dataset,
  File "~/DADA/evaluation/__init__.py", line 23, in evaluate
    computed_metrics, extra_infos = metric_computer.compute_standard(
  File "~/DADA/metrics/__init__.py", line 88, in compute_standard
    for idx, inp in enumerate(final_iter):
  File "~/lib/python3.9/site-packages/tqdm/std.py", line 1181, in __iter__
    for obj in iterable:
  File "~/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 633, in __next__
    data = self._next_data()
  File "~/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 1325, in _next_data
    return self._process_data(data)
  File "~/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 1371, in _process_data
    data.reraise()
  File "~/lib/python3.9/site-packages/torch/_utils.py", line 644, in reraise
    raise exception
FileNotFoundError: Caught FileNotFoundError in DataLoader worker process 2.
Original Traceback (most recent call last):
  File "~/lib/python3.9/site-packages/torch/utils/data/_utils/worker.py", line 308, in _worker_loop
    data = fetcher.fetch(index)
  File "~/lib/python3.9/site-packages/torch/utils/data/_utils/fetch.py", line 51, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "~/lib/python3.9/site-packages/torch/utils/data/_utils/fetch.py", line 51, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "~/DADA/datasets/basic_dataset.py", line 124, in __getitem__
    input_image = pil_ensure_3dim(Image.open(image_path))
  File "~/lib/python3.9/site-packages/PIL/Image.py", line 3227, in open
    fp = builtins.open(filename, "rb")
FileNotFoundError: [Errno 2] No such file or directory: '../dataset/online_products/images/cabinet_final/331185934232_10.JPG'
```
It seems that some images are missing.

**Comment by Noahsark** [comment]
@jjoon0928  

Hi,

For Cars196, did you download the data from the link I provided? There should be category folders under cars196/images (e.g. "cars196/images/Chevrolet\ Avalanche\ Crew\ Cab\ 2012/00044.jpg" should be a valid path). I will update the instruction to avoid the misleading.

For SOP, Sorry that I was not able to reproduce your error. Things work fine on my side.  Could you please check your permission for the data? Or check the version of all required packages.

Best,

**Comment by jjoon0928** [comment]
@Noahsark 
Hi.
I solved dataset issues what I mentioned above. Your advice was right about cars. 

For SOP, there was missing in some images due to dragging from finder to my server. I unzip it in my server and that was not any challenging. Thank you!

However, I have seen performance degradation when I use 'oproxy'

Recall@k values horribly decreased.

In "parameter.py", I change codes like:
```
73 parser.add_argument('--loss', default='oproxy', type=str, # default: dadaproxy, can change oproxy(PA, PNCA)
74                        help='Trainin objective to use. See folder <criteria> for available methods.')

...

141    parser.add_argument('--loss_oproxy_mode', default='nca', type=str, # nca or anchor
142                        help='Proxy-method: anchor = ProxyAnchor, nca = ProxyNCA.')

...

163    parser.add_argument('--samples_per_class', default=2, type=int,
164                        help='Number of samples in one class drawn before choosing the next class. Set to >1 for losses other than ProxyNCA.')
```

Are there any codes to change for ablation study? I just want to evaluate without adversarial things.\

Thank you.

**Comment by Noahsark** [comment]
@jjoon0928 

If you change the settings, you should search for optimal hyperparameters yourself. The "oproxy" is the original PA loss. You can refer to the hyperparameters reported in the PA paper. Or you can search better parameters by searching the lr, decay, margin values and other parameters.

**Comment by jjoon0928** [comment]
@Noahsark 

I adjusted hyperparameters based on PA method so the performance has been recovered. Thank you!
However, each datasets has different optimized hyperparameters. So, if I want to train each benchmarks. Should I change hyperparameters based on PA methods? 

Such as  DADA + PA(use optimized hyperparameters from PA), DADA + PNCA(use optimized hyperparameters from PA),  PA(use optimized hyperparameters from PA) and PNCA(use optimized hyperparameters from PA). 

Thank you!
